# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Mechanize-Plugin-phpBB
version:      0.01
version_from: lib/WWW/Mechanize/Plugin/phpBB.pm
installdirs:  site
requires:
    Class::Accessor:               0.19
    HTML::TreeBuilder:             0
    Log::Log4perl:                 1
    Module::Pluggable:             0
    WWW::Mechanize:                0
    WWW::Mechanize::Pluggable:     0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
